project:
  type: website
  output-dir: docs

website:
  title: "Kevin Li"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: kevin.qmd
        text: About me
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - posts.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

